export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const ADD_PRODUCT_INTO_CART = "ADD_PRODUCT_INTO_CART"
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART"
export const GET_CART_LIST = "GET_CART_LIST"

